services:
  - type: web
    name: music-rezyyy-bot
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: PATH
        value: /usr/local/bin:$PATH
