services:
  - type: web
    name: music-rezyyy-bot
    env: python
    region: oregon
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: PATH
        value: /usr/bin:/usr/local/bin:$PATH
